### ISSUE TITLE
Error: filesystem error: cannot get file time: No such file or directory [data/mods\S.T.A.L.K.E.R\NPC\Ð¼Ð¸Ñ.json]

### ISSUE THREAD

**Issue by FidzgeraldGrout** [Kenshut/CATACLYSM-S.T.A.L.K.E.R.#3]
**Описание ошибки:** 
Выдаёт ошибку при запуске
```
 DEBUG    : Error: filesystem error: cannot get file time: No such file or directory [data/mods\S.T.A.L.K.E.R\NPC\Ð¼Ð¸Ñ.json]

 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 945
 VERSION  : 2acc6f4
```
**Описание ос:** у меня вин 10, языковой регион - Казахстан, язык системы - русский.

**Предлагаемое исправление:** я думаю в папке NPC лежат два файла с наименованием на кириллице "мис" и "сюжет", может прописать их на латинице

**Comment by Kenshut** [comment]
у тебя не стабильная версия игры, последняя эксперементалка не любит русский, так что пошла она

**Comment by Kenshut** [comment]
а еще, ты скачивал через "Releases", или просто использовал копирование репозитория?

**Comment by FidzgeraldGrout** [comment]
да я просто обновил клиент через лаунчер. погуглив пару часов я скачал сборку **cdda-windows-tiles-sounds-x64-msvc-2023-05-06-0512** и как я понял скомпилированную на visual studio - так она вроде норм понимает кириллицу.

Но по моду всё равно баги пошли. правда не критичные. но есть ага

**Comment by Kenshut** [comment]
Так надо играть на стабилке

**Comment by Kenshut** [comment]
Вроде исправил, по крайней мере тестировал на версии 2023-04-01 и все стало работать
